ALTER TABLE anime ADD COLUMN banner_url VARCHAR(512) DEFAULT NULL AFTER description;
ALTER TABLE anime ADD COLUMN coverUrl VARCHAR(512) DEFAULT NULL AFTER banner_url;
ALTER TABLE anime ADD COLUMN trailerUrl VARCHAR(512) DEFAULT NULL AFTER coverUrl;
ALTER TABLE anime ADD COLUMN firstEp DATE DEFAULT NULL AFTER trailerUrl;