ALTER TABLE notifications MODIFY COLUMN type ENUM('FRIEND_REQUEST', 'SYSTEM', 'MESSAGE', 'GROUP_INVITE', 'REVIEW_LIKE', 'NEW_FOLLOWER') NOT NULL;
ALTER TABLE activities MODIFY COLUMN activity_type ENUM('ADDED_ANIME', 'COMPLETED_ANIME', 'REVIEWED_ANIME') NOT NULL;
ALTER TABLE reports MODIFY COLUMN target_type ENUM('REVIEW', 'THREAD', 'USER', 'COMMENT') NOT NULL;
ALTER TABLE reports MODIFY COLUMN status ENUM('PENDING', 'RESOLVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
